### ISSUE TITLE
Upgrade dependencies for low level security issues

### ISSUE THREAD

**Issue by dmitric** [chargehound/chargehound-slate#63]
These are two low level security issues as we do not serve this code directly in our application but rather use it as a processor

<img width="603" alt="Screen Shot 2020-04-28 at 10 56 13 AM" src="https://user-images.githubusercontent.com/201957/80502681-f1725100-893e-11ea-9dff-2dbf790569f3.png">

**Comment by jjjjw** [comment]
I think we just need to merge these PRs: 
![image](https://user-images.githubusercontent.com/1996632/82613409-10e54e00-9b7a-11ea-8223-b1776926c025.png)

After merging all 3 should just test a build

**Comment by jjjjw** [comment]
I merged all the dependabot PRs and rebuilt locally to validate
